import type { BridgeyConfig } from './types.js';

/**
 * Parse and normalize raw config JSON into a BridgeyConfig.
 *
 * Lives in its own module (rather than inline in index.ts) because index.ts
 * self-executes on import — extracting the parse/normalize step is the only way
 * to unit-test it.
 *
 * Normalization coerces `agents` to an array when absent. A minimal config
 * generated by the container entrypoint may omit it, and the daemon iterates
 * `config.agents` unconditionally on boot — an undefined value would throw
 * "config.agents is not iterable" and crash-loop the daemon. Normalizing at the
 * load boundary makes every downstream consumer safe.
 *
 * Returns null on invalid JSON or a non-object payload.
 */
export function parseConfig(raw: string): BridgeyConfig | null {
  let obj: unknown;
  try {
    obj = JSON.parse(raw);
  } catch {
    return null;
  }

  if (!obj || typeof obj !== 'object' || Array.isArray(obj)) {
    return null;
  }

  const c = obj as Partial<BridgeyConfig>;
  return {
    ...c,
    agents: Array.isArray(c.agents) ? c.agents : [],
  } as BridgeyConfig;
}
